/***********************************************************************************************************************
*
*	This is the header for module handle the event generated by inotifier.
*		
*	Continously reading the inotify_file for event, Extract the event that is generated on the file.	
*	Try to capture the change in the file or directory. 
*
*
*
*
*
************************************************************************************************************************/
#ifndef __HANDLE_NOTIFY__
	#define __HANDLE_NOTIFY__
	


#endif 
