/*****************************************************************************************************
 *
 *		@author:: 
 *		@Project:: DropBox for linux machine.
 *
 *
 *		Description:: This file contains the code that will syc the file with the server at the time of connection.
 *
 *
 *
 *
 *****************************************************************************************************/




#include "Client/HandleFileChange.h"
#include "Client/HandleNotifyEvent.h"
#include "Client/RegisterNotifier.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include "Common/CommandHeader.h"
#include "Common/FileTransfer.h"

int HandleEvent(int fdNotify, int connid, char *rootDirectory, int dropBoxId, int machineId);


//update the changed file on to the client. Send by the server.

void updateClientDropBox(HEADER* header, int connid, char *rootDirectory){

	if(!header||connid<0 ||!rootDirectory ){
		perror("Error in updatae ClientDropBox arguments\n");
		return ;
	}

	char name[1024];	//contains the name of the  file or directory heaving change.

	//It will receive the updated file, //check if it is the last file that is being recived.
	if(readBlock(connid, header, sizeof(HEADER))<0){
		perror("Not to able to read the first header from the server.\n");
		return ;
	}
	
	//check if there is no more file to get for update.
	while(!isNoMoreFile(header)){
		
		printf("run\n");
		int size = header->size;	//get the size of the file.
		
		//read the control info for the file.
		//read the name of the file.
		if(readBlock(connid, name, size)<0){
			perror("Not able to read the file name in while");
			return ;
		}	
		
		name[size]='\0';
		//check what operation has been occured.
		if(isNewFileCreated(header)){
			receiveServerNewFileCreation(connid, name, rootDirectory);
		}else if(isFileDeleted(header)){
			receiveServerFileDeletion(connid, name, rootDirectory);
		}/*else if(isFileMoved(header)){
			char *temp=&(name[strlen(name)+1]);
			receiveServerFileMoved(connid,name, temp, rootDirectory);	
		}*/else if(isFileModified(header)){
			receiveServerFileModify(connid, name,rootDirectory);
		}else if(isDirectoryCreated(header)){
			receiveServerDirectoryCreate(connid, name, rootDirectory);
		}/*else if(isDirectoryMoved(header)){
			char *temp=&(name[strlen(name)+1]);
			receiveServerDirectoryMoved(connid, name, temp, rootDirectory);
		}*/else if(isDirectoryDeleted(header)){
			receiveServerDirectoryRemoved(connid, name, rootDirectory);
		}else{
			perror("Something went wrong in file command.\n");
		}

		//after receiving the whole file, check if more file is there.
		if(readBlock(connid, header, sizeof(HEADER))<0){
			perror("Not to able to read the first header from the server.\n");
			return ; 
		} 
	}
	return;
}



//it will check the update from server.
int ClientConnectToDropBox(int dropBoxId, int machineId,int connid, char *rootDirectory){

	if(dropBoxId <0 || machineId<0||connid<0||!rootDirectory){
		perror("Error in ClientConnectToDropBox Arguments\n");
		return -1;
	}

	HEADER header;
	//char name[1024];
	int notify_id;

	header.dropBoxId = dropBoxId;
	header.machineId = machineId;
	
	
	resetFlag(&header);
	setInitialization(&header);
	
	//first header send to the server on connecting for the first time.
	//will read it and start sending the changed file for this machine.
	if(writeBlock(connid, &header, sizeof(header))<0){
		perror("Not able to send the initializatioin header.\n");
		return -1;
	}

	printf("Befor read\n");
	//for handling exclusive entry to dropBox.
	if(readBlock(connid, &header, sizeof(header))<0){
		perror("Error in reading the exit command\n");
		return -1;
	}
	printf("Before\n");
	if(isExitCommand(&header)){
		printf("Already a machine is Connected to Drop Box\n");
		return -1;
	}
	

	//printf("After Initializer write\n");	
	updateClientDropBox(&header,connid, rootDirectory);
	//printf("After Update DropBox\n");	
	//add the notifier for drop Box directory.
	//This will also generate the control structure for each file and directory in the drop box directory 
	//and store it inside the TRIE.
	
	notify_id=add_notifier(rootDirectory);

	if(notify_id<0){
		perror("Error in add_notfier\n");
		return -1;
	}	
	//handle the event generated by the changed file.
	HandleEvent(notify_id, connid, rootDirectory, dropBoxId, machineId);
	
	return 0;
}
